### PR TITLE
Qemu version bump and add support for encrypted VNC sessions

### PR DESCRIPTION
**Pull request by dkerr64**
Qemu is bumped to version 2.10.

Then I decided to try and get encrypted TLS VNC sessions working and that opened up a pandora's box as it requires gnutls package.  So I bump gnutls package to current version, which introduced new dependencies... so had to add packages nettle, liburistring and libtasn1.  And while at it lets bump up the other dependencies that gnutls has to their latest levels... gmp, libgcrypt and libgpg-error.  So these packages now all match the levels available from buildroot.

None of this stuff is selected by default but I have tested building with them and all build and run.  And I can now run VNC sessions over encrypted connection... you need a VNC client that supports encryption, I tested with TigerVNC and noVNC (browser-based).

### CODE REVIEW

**Comment by abelbeck** [comment]
I found a few issues:

- gnutls.mk references these packages we don't have:
```
BR2_PACKAGE_CRYPTODEV_LINUX
BR2_PACKAGE_P11_KIT
```
manually edit and follow the logic of the missing.

- package/Config.in not added alphabetically within their group

- We don't use `*_LICENSE*` variables, adds clutter

- You only updated 2 of the .config files ... I have a script to do that, so best to not include any .config updates

**Comment by dkerr64** [comment]
Thanks for the review.  I'll update.

**Comment by abelbeck** [comment]
Please remove the acme deploy changes with this PR, it was a NoOp until that.

**Comment by dkerr64** [comment]
Removed ACME deploy.  Sorry... was meant for my develop branch only.

**Comment by abelbeck** [comment]
Thanks, can't you configure qemu to use one of the other service certs ?

**Comment by dkerr64** [comment]
Unfortunately no.  All qemu lets you provide is path to a directory, the names of the certificates inside that directory are hardcoded... no way to specify what those are.  Not very flexible.

**Comment by abelbeck** [comment]
Possibly symlinks would work.

**Comment by dkerr64** [comment]
Thats a good idea but unfortunately none of the current astlinux services require the ca_cert to be deployed so there is nowhere for me to symlink to that.  And it seems that qemu requires all three certs in separate files.

I suppose I could symlink to /etc/acme/my.domain.name/acme-cert-files.  That would require me to know the domain name used to obtain the acme certificates.  Which I suppose I could assume is ${DOMAIN} from rc.conf (would work for me, but don't know if safe to assume that)

Of maybe the astlinux ACME deploy script should "deploy" all the certificates unmodified (so e.g. key and certs are not merged as done for e.g. lighttpd) into /mnt/kd/ssl and then any other service could point there with symlinks without needing to know what the domain name was.

**Comment by dkerr64** [comment]
Thanks Lonnie.  And thanks for the reviews and comments.

**Pull request merged**
